### ISSUE TITLE
添加多个字体 无法运行

### ISSUE THREAD

**Issue by lxwcv** [TKazer/OS-ImGui#2]
io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\msyh.ttc", 40, nullptr, io.Fonts->GetGlyphRangesChineseFull());
 io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\msyhbd.ttc", 40, nullptr, io.Fonts->GetGlyphRangesChineseFull());

如果设置一个字体 可以正常绘制  如果设置两个字体就会报错无法绘制
错误信息:Assertion failed: pTexture. != nul1ptr,guilimgui_impl_dx11.cpp，line 336
我目前还是学习阶段,请问这是什么原因

**Comment by TKazer** [comment]
``` c++
        ImFont* Font1 = ImGui::GetIO().Fonts->AddFontFromFileTTF(...);
        ImFont* Font2 = ImGui::GetIO().Fonts->AddFontFromFileTTF(...);

	ImGui::PushFont(Font1);
	// Drawing what you want.
	ImGui::PopFont();

        ImGui::PushFont(Font2);
	// Drawing what you want.
	ImGui::PopFont();
```
